# Generated by Django 2.0.9 on 2018-11-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thistests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='ask',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Тестирование', 'verbose_name_plural': 'Тестирования'},
        ),
        migrations.AlterModelOptions(
            name='name',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.IntegerField(verbose_name='Баллы за ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='ask',
            name='text',
            field=models.CharField(max_length=1000, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(max_length=2000, verbose_name='Вердикт'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_name',
            field=models.CharField(max_length=200, verbose_name='ФИО человека'),
        ),
        migrations.AlterField(
            model_name='game',
            name='total_score',
            field=models.IntegerField(verbose_name='Сумма баллов'),
        ),
        migrations.AlterField(
            model_name='name',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название теста'),
        ),
    ]
